name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [23.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn
      
    - name: Build
      run: yarn build

    - name: Create package
      run: ./build-upload.sh

    - uses: actions/upload-artifact@v4
      with:
        name: artifact-chrome-${{ matrix.node-version }}-${{ github.sha }}
        path: ./dist/chrome/

    - uses: actions/upload-artifact@v4
      with:
        name: artifact-firefox-${{ matrix.node-version }}-${{ github.sha }}
        path: ./dist/firefox/

    - uses: actions/upload-artifact@v4
      with:
        name: artifact-edge-${{ matrix.node-version }}-${{ github.sha }}
        path: ./dist/edge/
